mybatis: #mybatis配置
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: xyz.ezsky.entity
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydatabase.db
server: #程序访问端口号
  port: 8081
danDanWeb:
  scanPath: app/media/source
  targetPath: app/media/target/
  tempPath: app/media/temp/
  failedPath: app/media/source/failed/
  cron: 30 * * * * ?
danDanApi:
  match: https://api.dandanplay.net/api/v2/match
database:
  create:
    table:
      sql:
        file: createtable.sql
  file:
    path: app/config/database.db