mybatis: #mybatis配置
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: xyz.ezsky.entity
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydatabase.db
server: #程序访问端口号
  port: 8081
danDanWeb:
  scanPath: G:\动漫
  targetPath: G:\newanime\
  tempPath: G:\newanime\temp\
  failedPath: G:\newanime\failed\
  cron: 30 * * * * ?
danDanApi:
  match: https://api.dandanplay.net/api/v2/match
database:
  create:
    table:
      sql:
        file: createtable.sql
  file:
    path: database.db