mybatis: #mybatis配置
  mapper-locations: classpath:mappers/*.xml
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydatabase.db
server: #程序访问端口号
  port: 8081
danDanApi:
  match: https://api.dandanplay.net/api/v2/match
  anime: https://api.dandanplay.net/api/v2/bangumi
database:
  create:
    table:
      sql:
        file: createtable.sql
  file:
    path: app/config/database.db
pagehelper:
  helperDialect: sqlite
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
